version: '3.9'

#backup mysql
#backup mongodb
#reverse proxy
#ssl on reverse proxy
#proper storage of passwords
#storage/access to files not related to containers (crypto keys, app filesystem, app's config, etc)

#lib Essential Shared Libraries 
#var writeable directory for apps
#etc config files
#tmp temp files. deleted on pc restart

services:
    #dotnet
    webapp:
      #image: webbapp:1.22
      build:
        context: .
        dockerfile: dockerfile
      links: 
        - mongodb
      #environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://*:5001/
      depends_on:
      - proxy
      - sqldb
      - mongodb
      ports:
        - "5001:5001"
    #nginx
    #proxy:
    #  image: nginx:1.20
    #  volumes:
    #  - ./nginx.conf:/etc/nginx/nginx.conf
    #  ports:   
    #    - "80:80"

    #mariadb
    sqldb:
      image: mariadb:10.4.21
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
      - /var/lib/mysql
    mongodb:
      image: mongo:4.4.8
      ports:
        - "27017:27017"
      volumes:
      - /var/lib/mongodb
# volumes: 
#   mongo:
#   sql:
