version: '3.9'

#networks:
  #app-network:
    #driver: bridge

services:
    #dotnet
    webapp:
      #network_mode: host;
      image: webbapp:1.15
      #build: 
        #context: .
        #dockerfile: dockerfile

      depends_on:
      - proxy
      - sqldb
      - mongodb
     # networks:
       # - app-network
      ports:
        - "5001:5001"
    #nginx
    #proxy:
    #  image: nginx:1.20
    #  volumes:
    #  - ./nginx.conf:/etc/nginx/nginx.conf
    #  networks:
    #    - app-network
    #  ports:   
    #    - "80:80"

    #mariadb
    sqldb:
      image: mariadb:10.4.21
      environment:
        MYSQL_ROOT_PASSWORD: root
    #  networks:
     #   - app-network
    #mongodb
    mongodb:
      image: mongo:4.4.8
      container_name: mongo
      ports:
        - 27017:27017

     # networks:
       # - app-network

